// Auto-generated by scripts/bundle.sh — do not edit manually
enum BuildInfo {
    static let version = "1.0.0"
    static let gitHash = "71f48cd"
    static let gitDate = "2026-06-12 18:40:46 +0200"
    static let gitMessage = "docs: pre-release review fixes (guide overclaim, #30 changelog entry)"
    static let buildDate = "2026-06-12 18:41"
}
